/**
 * 组件列表：
 *   
 *  ActionSheet,
    AddressEdit,
    AddressList,
    Area,
    Button,
    Calendar,
    Card,
    Cell,
    CellGroup,
    Checkbox,
    CheckboxGroup,
    Circle,
    Col,
    Collapse,
    CollapseItem,
    ContactCard,
    ContactEdit,
    ContactList,
    CountDown,
    Coupon,
    CouponCell,
    CouponList,
    DatetimePicker,
    Divider,
    DropdownItem,
    DropdownMenu,
    Field,
    Form,
    GoodsAction,
    GoodsActionButton,
    GoodsActionIcon,
    Grid,
    GridItem,
    Icon,
    Image,
    ImagePreview,
    IndexAnchor,
    IndexBar,
    Info,
    Lazyload,
    List,
    Loading,
    Locale,
    NavBar,
    NoticeBar,
    NumberKeyboard,
    Overlay,
    Pagination,
    Panel,
    PasswordInput,
    Picker,
    Popup,
    Progress,
    PullRefresh,
    Radio,
    RadioGroup,
    Rate,
    Row,
    Search,
    Sidebar,
    SidebarItem,
    Skeleton,
    Sku,
    Slider,
    Step,
    Stepper,
    Steps,
    Sticky,
    SubmitBar,
    Swipe,
    SwipeCell,
    SwipeItem,
    Switch,
    SwitchCell,
    Tab,
    Tabbar,
    TabbarItem,
    Tabs,
    Tag,
    TreeSelect,
    Uploader,
    vuedraggable
 * 
 * 
 */

import {install}  from '@teld/component-proxy/export/mobile.js'


import {
    vuedraggable,ActionSheet,Button,Circle,Rate,Row
} from '@teld/component-proxy/mobile.js'


install([vuedraggable,ActionSheet,Button,Circle,Rate,Row])

